
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AGREGAR BATIR C CERNIR DECORAR ENFRIAR ENGRASAR GR HORNEAR IDENTIFICADOR IGUAL MEZCLAR ML NUMERO PRECALENTAR PUNTO_COMA REPETIR UN VECES VERTER\n    programa : instrucciones\n    \n    instrucciones : instrucciones instruccion\n    \n    instrucciones : instruccion\n    \n    instruccion : AGREGAR IDENTIFICADOR NUMERO unidad PUNTO_COMA\n    \n    instruccion : PRECALENTAR NUMERO C PUNTO_COMA\n    \n    instruccion : REPETIR NUMERO VECES accion PUNTO_COMA\n    \n    instruccion : IDENTIFICADOR IGUAL IDENTIFICADOR PUNTO_COMA\n    \n    unidad : ML\n    \n    unidad : GR\n    \n    unidad : UN\n    \n    accion : MEZCLAR\n    \n    accion : BATIR\n    \n    accion : HORNEAR\n    \n    accion : DECORAR\n    \n    accion : ENGRASAR\n    \n    accion : VERTER\n    \n    accion : ENFRIAR\n    \n    accion : CERNIR\n    '
    
_lr_action_items = {'AGREGAR':([0,2,3,8,21,22,32,33,],[4,4,-3,-2,-7,-5,-4,-6,]),'PRECALENTAR':([0,2,3,8,21,22,32,33,],[6,6,-3,-2,-7,-5,-4,-6,]),'REPETIR':([0,2,3,8,21,22,32,33,],[7,7,-3,-2,-7,-5,-4,-6,]),'IDENTIFICADOR':([0,2,3,4,8,10,21,22,32,33,],[5,5,-3,9,-2,14,-7,-5,-4,-6,]),'$end':([1,2,3,8,21,22,32,33,],[0,-1,-3,-2,-7,-5,-4,-6,]),'IGUAL':([5,],[10,]),'NUMERO':([6,7,9,],[11,12,13,]),'C':([11,],[15,]),'VECES':([12,],[16,]),'ML':([13,],[18,]),'GR':([13,],[19,]),'UN':([13,],[20,]),'PUNTO_COMA':([14,15,17,18,19,20,23,24,25,26,27,28,29,30,31,],[21,22,32,-8,-9,-10,33,-11,-12,-13,-14,-15,-16,-17,-18,]),'MEZCLAR':([16,],[24,]),'BATIR':([16,],[25,]),'HORNEAR':([16,],[26,]),'DECORAR':([16,],[27,]),'ENGRASAR':([16,],[28,]),'VERTER':([16,],[29,]),'ENFRIAR':([16,],[30,]),'CERNIR':([16,],[31,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'instrucciones':([0,],[2,]),'instruccion':([0,2,],[3,8,]),'unidad':([13,],[17,]),'accion':([16,],[23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> instrucciones','programa',1,'p_programa','parser_ply.py',15),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones_multiple','parser_ply.py',23),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones_simple','parser_ply.py',30),
  ('instruccion -> AGREGAR IDENTIFICADOR NUMERO unidad PUNTO_COMA','instruccion',5,'p_instruccion_agregar','parser_ply.py',39),
  ('instruccion -> PRECALENTAR NUMERO C PUNTO_COMA','instruccion',4,'p_instruccion_precalentar','parser_ply.py',64),
  ('instruccion -> REPETIR NUMERO VECES accion PUNTO_COMA','instruccion',5,'p_instruccion_repetir','parser_ply.py',81),
  ('instruccion -> IDENTIFICADOR IGUAL IDENTIFICADOR PUNTO_COMA','instruccion',4,'p_instruccion_asignacion','parser_ply.py',97),
  ('unidad -> ML','unidad',1,'p_unidad_ml','parser_ply.py',112),
  ('unidad -> GR','unidad',1,'p_unidad_gr','parser_ply.py',119),
  ('unidad -> UN','unidad',1,'p_unidad_un','parser_ply.py',126),
  ('accion -> MEZCLAR','accion',1,'p_accion_mezclar','parser_ply.py',133),
  ('accion -> BATIR','accion',1,'p_accion_batir','parser_ply.py',140),
  ('accion -> HORNEAR','accion',1,'p_accion_hornear','parser_ply.py',147),
  ('accion -> DECORAR','accion',1,'p_accion_decorar','parser_ply.py',154),
  ('accion -> ENGRASAR','accion',1,'p_accion_engrasar','parser_ply.py',161),
  ('accion -> VERTER','accion',1,'p_accion_verter','parser_ply.py',168),
  ('accion -> ENFRIAR','accion',1,'p_accion_enfriar','parser_ply.py',175),
  ('accion -> CERNIR','accion',1,'p_accion_cernir','parser_ply.py',182),
]
